* makes sure memory is clear
clear
* keeps 
capture log close
set more off
*
* Analyze the Roy model in some simulation 
*
*
log using anRoyModelSample.log, replace
*
* Set up data simulation dataset.  Set seed so we may replicate this program 
*

*********************************************************************************************


set seed 195912191

*
* Set covariance matrix for Standard normal random variables
*
matrix V = (1, .9 \ .9, 1)
* draw bivariate normal with n = 1,000,000
drawnorm za ze, cov(V) n(1000000) 
*
* y1 economists y0 accountant mean 60k for econ, 65k for acct
* sd econ 10,000 and 5,000 for acct
*
gen y1 = 60000 + 10000*ze


gen y0 = 65000 +  5000*za
*summarize the data
sum y1 y0
* pick the field that pays the most
gen y = max(y0,y1)
* summarize observed earnings
sum y 
* d=1 means economics, d=0 accounting
gen d = y1 > y0
* run cross tables
tab d
tab d, sum(y)
* selection into y0
tab d, sum(y0)
* selection into y1
tab d, sum(y1)

*

*Answer for Question1
*Two reasons:
*Seed is different in R and Stata. Seed is a dynamic number that can be set which allows us to replicate the observations generated by the random number generator. It is helpful for simulations to replicate the results which can aid simulation analysis. 
*However, even with same seed, different results are observed in R and Stata. This can be because the Normal distribution generated in R differs from what is generated in Stata. 
*This shows that the underlying distribution generator algorithm functions differently in R(mvrnorm) and Stata(drawnorm).
*



*************************************************************************

* makes sure memory is clear
clear

*Question2
	*Change the seed 
	*set seed 02101870
*Question2


set seed 195912191

*
* Set covariance matrix for Standard normal random variables
*
matrix V = (1, .9 \ .9, 1)
* draw bivariate normal with n = 1,000,000
drawnorm za ze, cov(V) n(1000000) 
*
* y1 economists y0 accountant mean 60k for econ, 65k for acct
* sd econ 10,000 and 5,000 for acct
*
gen y1 = 60000 + 10000*ze


gen y0 = 65000 +  5000*za
*summarize the data
sum y1 y0
* pick the field that pays the most
gen y = max(y0,y1)
* summarize observed earnings
sum y 
* d=1 means economics, d=0 accounting
gen d = y1 > y0
* run cross tables
tab d
tab d, sum(y)
* selection into y0
tab d, sum(y0)
* selection into y1
tab d, sum(y1)



*Answer for Question 2
*Reset the seed to original seed value 195912191
*1) Reason for not giving birthdate of self could be construed a data privacy issue or data security issue. Also it will produce similar results as fellow mates in the class because the birthday paradox shows that their is a greater probablity for repition of birthday when the sample size exceeds 23.
*2) Seed set is different in question 1 and question 2. As seed is changed, the distribution generated changes slightly causing the results to change slightly.
	*However the mean and variance still remains same as they are fixed. Only the observations changes with change in seed.







*********************************************************************************
* makes sure memory is clear
clear


set seed 195912191

*
* Set covariance matrix for Standard normal random variables
*
matrix V = (1, .9 \ .9, 1)
* draw bivariate normal with n = 1,000,000
drawnorm za ze, cov(V) n(1000000) 
*
* y1 economists y0 accountant mean 60k for econ, 65k for acct
* sd econ 10,000 and 5,000 for acct
*
gen y1 = 60000 + 10000*ze

gen y0 = 65000 +  5000*za
*summarize the data
sum y1 y0
* pick the field that pays the most
gen y = max(y0,y1)
* summarize observed earnings
sum y 
* d=1 means economics, d=0 accounting
gen d = y1 > y0
* run cross tables
tab d
tab d, sum(y)
* selection into y0
tab d, sum(y0)
* selection into y1
tab d, sum(y1)

*

**Answer for Question 3
*The standard normal samle size is 1000000
*It is observed that out of the sample size for economists only 198340 have become economists and hence the standard deviation we observed (5693.8071) is significantly less compared to the conditional standard deviation of 100000
*The same goes for accountants, out of the sample size for accountants its observed that 801660 have become accountants, hence the standard deviation we observed (4499.5368) is less compared to the conditional standard deviation set of 5000





*********************************************************************************

* makes sure memory is clear
clear

*Question4
	*Change the standard deviation of Economist earnings to 12000 from 10000
	* gen y1 = 60000 + 12000*ze
*Question4


set seed 195912191

*
* Set covariance matrix for Standard normal random variables
*
matrix V = (1, .9 \ .9, 1)
* draw bivariate normal with n = 1,000,000
drawnorm za ze, cov(V) n(1000000) 
*
* y1 economists y0 accountant mean 60k for econ, 65k for acct
* sd econ 10,000 and 5,000 for acct
*
gen y1 = 60000 + 12000*ze

gen y0 = 65000 +  5000*za
*summarize the data
sum y1 y0
* pick the field that pays the most
gen y = max(y0,y1)
* summarize observed earnings
sum y 
* d=1 means economics, d=0 accounting
gen d = y1 > y0
* run cross tables
tab d
tab d, sum(y)
* selection into y0
tab d, sum(y0)
* selection into y1
tab d, sum(y1)

*Answer to question 4
*The data shows an increase in total economists and decrease in accountants. As the standard deviation of economist earnings is increased from $10000 to $12000, the economist earnings of economist have increased and accountants with economist earnings have reduced. This is due to the flattening of the curve that happens because of the increase in standard deviation causing the occurrences of high economist earnings has increased resulting more total economists and less total accountants. Due to the same, the mean of economists with economist earnings increases (Mean changed from 73053.0.32  to 74353.441 ) whereas the mean of accountants with accountant earnings has reduced(Mean changed from 63826.404 to 63369.132). One another observation is the increase in people with economists earnings (198340 to 260672) and reduction in number of people with accountants earnings (801660 to 739328)


*********************************************************


*
log close
*

translate anRoyModelSample.log anRoyModelSample.pdf